export const asset = (fileName: string) => `/assets/${fileName}`;

export const icons = {
  lotusLogo: asset('lotus-logo-navy.png'),
  gift: asset('gift-outline.png'),
  sparkleGold: asset('sparkle-gold.png'),
  sparkleSoftGold: asset('sparkle-soft-gold.png'),
  sparkleCoral: asset('sparkle-coral.png'),
  sparklePurple: asset('sparkle-purple.png'),
  sparkleLilacOutline: asset('sparkle-lilac-outline.png'),
  backCircleBlue: asset('back-circle-blue.png'),
  backSmallBlue: asset('back-circle-small-blue.png'),
  backSquareGold: asset('back-square-gold.png'),
  closeCircleBlue: asset('close-circle-blue.png'),
  calendarStar: asset('calendar-star-chip.png'),
  calendarNavy: asset('calendar-star-navy.png'),
  venus: asset('venus-symbol.png'),
  lock: asset('lock-navy.png'),
  privacyLock: asset('privacy-lock-badge.png'),
  homePurple: asset('home-purple.png'),
  homeGold: asset('home-gold.png'),
  userGray: asset('user-outline-gray.png'),
  userBlueGray: asset('user-outline-bluegray.png'),
  avatarWoman: asset('avatar-woman.png'),
  selectedCheck: asset('selected-check-badge.png'),
  dividerGold: asset('divider-gold-long.png'),
  dividerPurple: asset('divider-purple-tiny.png'),
  dividerCelestial: asset('divider-celestial-wide.png'),
  gradientStrip: asset('gradient-strip.png'),
  infoPurple: asset('info-purple.png'),
  heart: asset('heart-outline.png'),
  scales: asset('scales-navy.png'),
  shield: asset('shield-growth.png'),
  dress: asset('dress-outline.png'),
  chat: asset('chat-outline.png'),
  flowerPink: asset('flower-pink.png'),
};

export const moodIcons = {
  drained: asset('mood-drained-drop.png'),
  soft: asset('mood-soft-cloud.png'),
  restless: asset('mood-restless-swirl.png'),
  hidden: asset('mood-hidden-eye-slash.png'),
  focused: asset('mood-focused-target.png'),
  magnetic: asset('mood-magnetic-sparkle.png'),
  unbothered: asset('mood-unbothered-lotus.png'),
  mainCharacter: asset('mood-main-character-crown.png'),
};

export const intentIcons = {
  workStudy: asset('intent-work-study-book.png'),
  stayLowKey: asset('intent-stay-low-key-lock.png'),
  needProtection: asset('intent-need-protection-shield.png'),
  wantToBeSeen: asset('intent-want-to-be-seen-eye.png'),
  social: asset('intent-social-people.png'),
  softReset: asset('intent-soft-reset-arrows.png'),
};

export const art = {
  tarotCardBack: asset('tarot-card-back-card2.png'),
  tarotCardTilt: asset('tarot-card-back-tilt.png'),
  auraOrb: asset('aura-orb-cloud.png'),
  cloudsGlow: asset('clouds-glow-wide.png'),
  progressTrack: asset('progress-track-gradient.png'),
  pinkGlowBg: asset('pink-glow-card-bg.png'),
  pickerGlassBg: asset('picker-glass-bg.png'),
  softCardBg: asset('soft-pink-lavender-card-bg.png'),
  strengthWomanLion: asset('strength-woman-lion-card.png'),
  lotusPink: asset('lotus-pink-glow.png'),
  sealOrbPink: asset('seal-orb-pink.png'),
  birthAuraVenusAir: asset('birth-aura-venus-air-orb.png'),
  softOpalSwatch: asset('soft-opal-pink-swatch.png'),
  libraBadge: asset('libra-badge-gold.png'),
  prepCrystal: asset('prep-crystal.png'),
  prepPlanet: asset('prep-planet.png'),
  prepMoon: asset('prep-moon.png'),
  prepStar: asset('prep-star.png'),
  charcoalNavySwatch: asset('soft-opal-pink-swatch.png'),
};
