const asset = (name: string) => `/assets/${name}`;

export const icons = {
  drop: asset('drop.png'),
  cloud: asset('cloud.png'),
  swirl: asset('swirl.png'),
  eyeSlash: asset('eye_slash.png'),
  target: asset('target.png'),
  sparkleLine: asset('sparkle_line.png'),
  lotusLine: asset('lotus_line.png'),
  crown: asset('crown.png'),
  book: asset('book.png'),
  lock: asset('lock.png'),
  shield: asset('shield.png'),
  eye: asset('eye.png'),
  people: asset('people.png'),
  refresh: asset('refresh.png'),
  checkBadge: asset('check_badge.png'),
  venusSymbol: asset('venus_symbol.png'),
  calendarStar: asset('calendar_star.png'),
  lotusLogo: asset('lotus_logo.png'),
  goldSparkle: asset('gold_sparkle.png'),
  goldStar: asset('gold_star.png'),
  homePurple: asset('home_purple.png'),
  homeGold: asset('home_gold.png'),
  userGray: asset('user_gray.png'),
  userOutline: asset('user_outline.png'),
  avatarWoman: asset('avatar_woman.png'),
  backBlueRound: asset('back_blue_round.png'),
  backPinkRound: asset('back_pink_round.png'),
  backGoldSquare: asset('back_gold_square.png'),
  gradientButton: asset('gradient_button.png'),
  gradientPanelWide: asset('gradient_panel_wide.png'),
  softGradientPanel: asset('soft_gradient_panel.png'),
  heroWoman: asset('hero_woman_lion.png'),
  crystalMedallion: asset('crystal_medallion.png'),
  planetMedallion: asset('planet_medallion.png'),
  moonMedallion: asset('moon_medallion.png'),
  starMedallion: asset('star_medallion.png'),
  pinkLotus: asset('pink_lotus.png'),
  pinkOrb: asset('pink_orb.png'),
  softOpalSwatch: asset('soft_opal_swatch.png'),
  libraSymbol: asset('libra_symbol.png'),
  birthLotusMedallion: asset('birth_lotus_medallion.png'),
  infoIcon: asset('info_icon.png'),
  dividerGold: asset('divider_gold.png'),
  dividerSmall: asset('divider_small.png'),
  purpleSparkle: asset('purple_sparkle.png'),
  heartPink: asset('heart_pink.png'),
  lockBadge: asset('lock_badge.png'),
  flowerPink: asset('flower_pink.png')
} as const;

export type IconKey = keyof typeof icons;
